"""remove unique constraint in job_url column

Revision ID: 1ebb92ab84c3
Revises: 9c94a5d22911
Create Date: 2026-08-27 06:34:36.873196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebb92ab84c3'
down_revision: Union[str, Sequence[str], None] = '9c94a5d22911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jobs_job_url_key'), 'jobs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('jobs_job_url_key'), 'jobs', ['job_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
