"""added job_url_id in job table

Revision ID: 9c94a5d22911
Revises: dfe7a9bad287
Create Date: 2026-08-26 06:23:28.070640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c94a5d22911'
down_revision: Union[str, Sequence[str], None] = 'dfe7a9bad287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('job_url_id', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'job_url_id')
    # ### end Alembic commands ###
