"""modified skills and job_skills table

Revision ID: dfe7a9bad287
Revises: 81c9b23b607a
Create Date: 2026-08-24 15:05:19.345331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dfe7a9bad287'
down_revision: Union[str, Sequence[str], None] = '81c9b23b607a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.drop_index(op.f('ix_job_required_skills_job_id'), table_name='job_required_skills')
    op.drop_index(op.f('ix_job_required_skills_skill_id'), table_name='job_required_skills')
    op.drop_table('job_required_skills')
    op.drop_index(op.f('ix_job_preferred_skills_job_id'), table_name='job_preferred_skills')
    op.drop_index(op.f('ix_job_preferred_skills_skill_id'), table_name='job_preferred_skills')
    op.drop_table('job_preferred_skills')
    op.execute('DELETE FROM job_skills')
    op.add_column('job_skills', sa.Column('job_id', sa.String(length=36), nullable=False))
    op.add_column('job_skills', sa.Column('skill_id', sa.String(length=36), nullable=False))
    op.add_column('job_skills', sa.Column('skill_type', sa.String(length=20), nullable=False))
    op.drop_index(op.f('ix_job_skills_name'), table_name='job_skills')
    op.create_index(op.f('ix_job_skills_job_id'), 'job_skills', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_skills_skill_id'), 'job_skills', ['skill_id'], unique=False)
    op.create_foreign_key(None, 'job_skills', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(None, 'job_skills', 'skills', ['skill_id'], ['id'])
    op.drop_column('job_skills', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_skills', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.drop_index(op.f('ix_job_skills_skill_id'), table_name='job_skills')
    op.drop_index(op.f('ix_job_skills_job_id'), table_name='job_skills')
    op.create_index(op.f('ix_job_skills_name'), 'job_skills', ['name'], unique=True)
    op.drop_column('job_skills', 'skill_type')
    op.drop_column('job_skills', 'skill_id')
    op.drop_column('job_skills', 'job_id')
    op.create_table('job_preferred_skills',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_preferred_skills_job_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['job_skills.id'], name=op.f('job_preferred_skills_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_preferred_skills_pkey'))
    )
    op.create_index(op.f('ix_job_preferred_skills_skill_id'), 'job_preferred_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_job_preferred_skills_job_id'), 'job_preferred_skills', ['job_id'], unique=False)
    op.create_table('job_required_skills',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_required_skills_job_id_fkey')),
    sa.ForeignKeyConstraint(['skill_id'], ['job_skills.id'], name=op.f('job_required_skills_skill_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('job_required_skills_pkey'))
    )
    op.create_index(op.f('ix_job_required_skills_skill_id'), 'job_required_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_job_required_skills_job_id'), 'job_required_skills', ['job_id'], unique=False)
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
